# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' @noRd
#' 
NULL

VB_GFMcpp <- function(XList, typeID, A, Mu_y_int, S_y_int, invLambda_int, B_int, mu_int, Mu_h_int, S_h_int, Sigma_h_int, epsELBO, maxIter, verbose) {
    .Call(`_GFM_VB_GFMcpp`, XList, typeID, A, Mu_y_int, S_y_int, invLambda_int, B_int, mu_int, Mu_h_int, S_h_int, Sigma_h_int, epsELBO, maxIter, verbose)
}

